name: Update HoYoPlay Backgrounds

on:
  schedule:
    - cron: '0 3 * * *'    # daily at 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-backgrounds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create scripts folder
        run: mkdir -p .github/scripts

      - name: Write updater script
        run: |
          cat > .github/scripts/update-hoyoplay-bg.js <<'EOF'
          const fs = require('fs');
          const path = require('path');

          (async () => {
            try {
              const API = 'https://sg-hyp-api.hoyoverse.com/hyp/hyp-connect/api/getAllGameBasicInfo?launcher_id=VYTpXlbWo8&language=en-us&game_id=gopR6Cufr3';
              const outDir = path.join(process.cwd(), 'Background');
              if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

              console.log('Fetching API...');
              const res = await fetch(API, { headers: { 'User-Agent': 'github-action' } });
              if (!res.ok) throw new Error('API fetch failed ' + res.status);
              const j = await res.json();
              const list = j?.data?.game_info_list || [];
              if (!list.length) throw new Error('no game_info_list');
              const backgrounds = list[0].backgrounds || [];
              const urls = backgrounds.map(b => (b && b.background && b.background.url) || b?.url).filter(Boolean);

              const first = urls[0];
              const second = urls[1] || urls[0];

              if (!first) throw new Error('no background urls found');

              async function downloadTo(url, outPath) {
                console.log('Downloading', url);
                const r = await fetch(url, { headers: { 'User-Agent': 'github-action' } });
                if (!r.ok) throw new Error('download failed ' + r.status);
                const buf = Buffer.from(await r.arrayBuffer());
                fs.writeFileSync(outPath, buf);
                console.log('Saved', outPath);
              }

              await downloadTo(first, path.join(outDir, 'image1.webp'));
              await downloadTo(second, path.join(outDir, 'image2.webp'));

              // commit & push changes
              const execSync = require('child_process').execSync;
              execSync('git config user.name "github-actions[bot]"');
              execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"');
              execSync('git add ' + path.join('Background','image1.webp') + ' ' + path.join('Background','image2.webp'));
              try { execSync('git commit -m "Auto-update HoYoPlay backgrounds"'); } catch(e) { console.log('No changes to commit'); }
              execSync('git push');
              console.log('Done');
            } catch (e) {
              console.error(e);
              process.exit(1);
            }
          })();
          EOF

      - name: Run updater
        env:
          NODE_OPTIONS: --unhandled-rejections=strict
        run: node .github/scripts/update-hoyoplay-bg.js
